sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t preedalakshmi/react-test -f ./client/Dockerfile.dev ./client
script:
     # - docker run -e CI=true preedalakshmi/react-test npm test -- --coverage
  - docker run -e CI=true preedalakshmi/react-test npm test
after_success:
  - docker build preedalakshmi/multi-client ./client
  - docker build preedalakshmi/multi-ngnix ./ngnix
  - docker build preedalakshmi/multi-server ./server
  - docker build preedalakshmi/multi-worker ./worker
        #login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push preedalakshmi/multi-client
  - docker push preedalakshmi/multi-ngnix
  - docker push preedalakshmi/multi-server
  - docker push preedalakshmi/multi-worker