sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t preedalakshmi/react-test -f ./client/Dockerfile.dev ./client
script:
     # - docker run -e CI=true preedalakshmi/react-test npm test -- --coverage
  - docker run -e CI=true preedalakshmi/react-test npm test
after_success:
  - docker build -t preedalakshmi/multi-client ./client
  - docker build -t preedalakshmi/multi-ngnix ./ngnix
  - docker build -t preedalakshmi/multi-server ./server
  - docker build -t preedalakshmi/multi-worker ./worker
        #login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push preedalakshmi/multi-client
  - docker push preedalakshmi/multi-ngnix
  - docker push preedalakshmi/multi-server
  - docker push preedalakshmi/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-582668956449
  bucket_path: dockeer-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
